server:
  port: 8080
spring:
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          format_sql: true

    sql:
      init:
        mode: always

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/ewm_db
      username: postgres
      password: pass
