spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url:               jdbc:postgresql://localhost:5432/stats_db
    username:          postgres
    password:          pass

server:
  port: 9090
